# Generated by Django 3.2.8 on 2021-10-26 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('event_date', models.DateTimeField()),
                ('expiration_event_date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
