# Generated by Django 3.2.8 on 2021-10-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20211027_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('next', 'Next'), ('in process', 'In process'), ('carried out', 'Carried out'), ('postponed', 'Postponed'), ('finalized', 'Finalized')], max_length=15),
        ),
    ]
