# Generated by Django 3.2.8 on 2021-10-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmuser',
            name='history_last_access',
        ),
    ]
