# Generated by Django 3.2.8 on 2021-10-21 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_client_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 21, 20, 1, 52, 37144, tzinfo=utc)),
        ),
    ]
