# Generated by Django 3.2.8 on 2021-10-21 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_client_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='register_date',
            field=models.DateField(default=datetime.date(2021, 10, 21)),
        ),
    ]
