# Generated by Django 3.2.8 on 2021-10-21 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_client_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
