# Generated by Django 3.2.8 on 2021-10-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_client_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='process_sale_status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('await', 'await'), ('Trained', 'Trained'), ('Registered', 'Registered'), ('close', 'close')], max_length=50),
        ),
    ]
