# Generated by Django 3.2.8 on 2021-10-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_client_register_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='other_social_network',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_status',
        ),
        migrations.AddField(
            model_name='sale',
            name='commission',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('successfully', 'successfully'), ('in process', 'in process'), ('no successfully.', 'no successfully')], default='in process', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='update_sale',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.BooleanField(choices=[(True, 'Is client'), (False, 'Not Client')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='process_sale_status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('await', 'await'), ('Trained', 'Trained'), ('Registered', 'Registered'), ('close', 'close')], max_length=50),
        ),
    ]
