# Generated by Django 3.2.8 on 2021-10-27 16:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20211026_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='sale',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
