# Generated by Django 3.2.8 on 2021-10-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_sale_process_sale_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_status',
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('successfully', 'successfully'), ('in process', 'in process'), ('no successfully.', 'no successfully')], default='in process', max_length=50),
            preserve_default=False,
        ),
    ]
