# Generated by Django 3.2.8 on 2021-11-01 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20211027_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
