# Generated by Django 3.2.8 on 2021-10-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20211022_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.BooleanField(choices=[(True, 'Is client'), (False, 'Not Client')]),
        ),
    ]
